site_name: BlackPHP
site_url: https://manuales.algoritmia.sv/blackphp/
site_description: Manual de usuario de BlackPHP
site_author: Edwin Fajardo
copyright: Copyright &copy;2024 Algoritmia SV
site_dir: /store/bphp/manuals/blackphp
nav:
  - Inicio: index.md
  - Usuario: usuario.md
  - Herramientas:
    - 'Historial de actividades': herramientas/historial-actividades.md
    - 'Papelera de reciclaje': herramientas/papelera.md
  - Configuraciones:
    - 'Datos de la empresa': configuraciones/entidad.md
    - Preferencias: configuraciones/preferencias.md
    - Roles: configuraciones/roles.md
    - Usuarios: configuraciones/usuarios.md
theme:
  name: mkdocs
  nav_style: dark
  locale: es
extra_css:
  - css/algoritmiasv.css
markdown_extensions:
  - attr_list
